package fr.aphp.sashimi.writer

import fr.aphp.sashimi.mapper.StructureDefinitionMapper
import fr.aphp.sashimi.parser.SqlTableParser
import org.junit.jupiter.api.Assertions.*
import org.junit.jupiter.api.DynamicTest
import org.junit.jupiter.api.DynamicTest.dynamicTest
import org.junit.jupiter.api.Nested
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.TestFactory

class FshWriterTest {
    private val parser = SqlTableParser()
    private val mapper = StructureDefinitionMapper()
    private val writer = FshWriter()

    // ── Helpers ───────────────────────────────────────────────────────────

    private fun fsh(ddl: String): String = writer.write(mapper.map(parser.parse(ddl.trimIndent())).successes.first())

    private fun assertContains(
        fsh: String,
        vararg snippets: String,
    ) = snippets.forEach { assertTrue(fsh.contains(it), "FSH should contain: «$it»\n\nProduced FSH:\n$fsh") }

    // ── Basic skeleton ─────────────────────────────────────────────────

    @Nested
    inner class Header {
        @Test
        fun `contains the Sashimi comment`() {
            val fsh = fsh("CREATE TABLE t (id UUID NOT NULL);")
            assertContains(fsh, "Auto-generated by Sashimi")
        }

        @Test
        fun `Logical keyword is present`() {
            assertContains(fsh("CREATE TABLE patient (id UUID NOT NULL);"), "Logical: Patient")
        }

        @Test
        fun `Id is lowercase`() {
            assertContains(fsh("CREATE TABLE MyTable (id UUID NOT NULL);"), "Id: mytable")
        }

        @Test
        fun `snake_case table converted to PascalCase`() {
            assertContains(fsh("CREATE TABLE care_site (id UUID NOT NULL);"), "Logical: CareSite")
        }
    }

    // ── Cardinality ───────────────────────────────────────────────────────

    @Nested
    inner class Cardinality {
        @Test
        fun `NOT NULL produces cardinality 1 dot 1`() {
            assertContains(fsh("CREATE TABLE t (col TEXT NOT NULL);"), "* col 1..1")
        }

        @Test
        fun `nullable column produces cardinality 0 dot 1`() {
            assertContains(fsh("CREATE TABLE t (col TEXT);"), "* col 0..1")
        }

        @Test
        fun `several columns with mixed cardinalities`() {
            val fsh =
                fsh(
                    """
                CREATE TABLE t (
                    a TEXT NOT NULL,
                    b TEXT,
                    c INT NOT NULL
                );
            """,
                )
            assertContains(fsh, "* a 1..1", "* b 0..1", "* c 1..1")
        }
    }

    // ── SQL → FHIR type mapping ───────────────────────────────

    @Nested
    inner class TypeMapping {
        @TestFactory
        fun `primitive SQL types to FHIR`(): List<DynamicTest> =
            listOf(
                "UUID" to "uuid",
                "TEXT" to "string",
                "VARCHAR(50)" to "string",
                "INT" to "integer",
                "INTEGER" to "integer",
                "BIGINT" to "integer",
                "NUMERIC" to "decimal",
                "DECIMAL" to "decimal",
                "BOOLEAN" to "boolean",
                "DATE" to "date",
                "TIMESTAMP" to "dateTime",
            ).map { (sqlType, fhirType) ->
                dynamicTest("$sqlType → $fhirType") {
                    val fsh = fsh("CREATE TABLE t (col $sqlType NOT NULL);")
                    // Unwrapped (column with no fact) or under ".value" (e.g. INT/INTEGER/BIGINT, whose
                    // default jOOQ type carries a non-null precision even without an explicit clause in
                    // the DDL — the column is then wrapped, like `a`/`b` in the anonymous-constraints
                    // fixture).
                    assertTrue(
                        fsh.contains("* col 1..1 $fhirType") || fsh.contains("* col.value 1..1 $fhirType"),
                        "FSH should map $sqlType to $fhirType (with or without a BackboneElement wrapper)\n\nProduced FSH:\n$fsh",
                    )
                }
            }

        @Test
        fun `primary UUID column produces uuid type under value`() {
            val fsh =
                fsh(
                    """
                CREATE TABLE t (
                    id UUID NOT NULL,
                    CONSTRAINT pk_t PRIMARY KEY (id)
                );
            """,
                )
            // PK -> wrapped column: the original SQL type migrates to the ".value" child.
            assertContains(fsh, "* id 1..1 BackboneElement", "* id.value 1..1 uuid")
        }
    }

    // ── Primary key ──────────────────────────────────────────────────────

    @Nested
    inner class PrimaryKey {
        private val ddl = """
            CREATE TABLE patient (
                id UUID NOT NULL,
                CONSTRAINT pk_patient PRIMARY KEY (id)
            );
        """

        @Test
        fun `PK column wrapped in BackboneElement with isPrimaryKey child fixed to true`() {
            assertContains(
                fsh(ddl),
                "* id 1..1 BackboneElement",
                "* id.isPrimaryKey 1..1 boolean",
                "* id.isPrimaryKey = true",
            )
        }

        @Test
        fun `isPrimaryKey absent on non-PK columns`() {
            val fsh =
                fsh(
                    """
                CREATE TABLE t (
                    id   UUID NOT NULL,
                    name TEXT NOT NULL,
                    CONSTRAINT pk_t PRIMARY KEY (id)
                );
            """,
                )
            // isPrimaryKey must be declared only once (for id); name stays a primitive element.
            assertEquals(
                1,
                fsh.lines().count { it.contains("isPrimaryKey 1..1 boolean") },
                "isPrimaryKey must be declared exactly once",
            )
            assertContains(fsh, "* name 1..1 string")
        }

        @Test
        fun `composite PK emitted on each column concerned`() {
            val fsh =
                fsh(
                    """
                CREATE TABLE t (
                    col_a INT NOT NULL,
                    col_b INT NOT NULL,
                    CONSTRAINT pk_t PRIMARY KEY (col_a, col_b)
                );
            """,
                )
            assertEquals(
                2,
                fsh.lines().count { it.contains("isPrimaryKey 1..1 boolean") },
                "composite PK: isPrimaryKey expected on 2 columns",
            )
            assertEquals(
                2,
                fsh.lines().count { it.trim() == "* colA.isPrimaryKey = true" || it.trim() == "* colB.isPrimaryKey = true" },
                "composite PK: each column must fix isPrimaryKey to true",
            )
        }
    }

    // ── Foreign key ─────────────────────────────────────────────────────

    @Nested
    inner class ForeignKey {
        private val ddl = """
            CREATE TABLE encounter (
                id         UUID NOT NULL,
                patient_id UUID,
                CONSTRAINT pk_encounter  PRIMARY KEY (id),
                CONSTRAINT fk_patient    FOREIGN KEY (patient_id) REFERENCES patient(id)
            );
        """

        @Test
        fun `FK produces a Reference type`() {
            assertContains(fsh(ddl), "Reference(")
        }

        @Test
        fun `fk1 group emitted with reference and targetColumn fixed to the target column`() {
            assertContains(
                fsh(ddl),
                "* patientId 0..1 BackboneElement",
                "* patientId.fk1 1..1 BackboneElement",
                "* patientId.fk1.reference 1..1 Reference(",
                "* patientId.fk1.targetColumn 1..1 string",
                "* patientId.fk1.targetColumn = \"id\"",
            )
        }

        @Test
        fun `column without FK remains a primitive type`() {
            val fsh = fsh(ddl)
            // id must not be a Reference
            val idLine = fsh.lines().first { it.trimStart().startsWith("* id ") }
            assertFalse(idLine.contains("Reference"), "id should not be a Reference")
        }
    }

    // ── CHECK constraints → invariants ────────────────────────────────────

    @Nested
    inner class Invariants {
        private val ddl = """
            CREATE TABLE encounter (
                id         UUID      NOT NULL,
                start_date TIMESTAMP NOT NULL,
                note       TEXT,
                CONSTRAINT pk_encounter PRIMARY KEY (id),
                CONSTRAINT chk_note CHECK (note IS NOT NULL OR start_date IS NOT NULL)
            );
        """

        @Test
        fun `obeys emitted for each CHECK constraint`() {
            assertContains(fsh(ddl), "* obeys chk-note")
        }

        @Test
        fun `full invariant block generated`() {
            val fsh = fsh(ddl)
            assertContains(
                fsh,
                "Invariant: chk-note",
                "Description: \"(note IS NOT NULL OR startDate IS NOT NULL)\"",
                "Expression: \"true\"",
                "Severity: #error",
            )
        }

        @Test
        fun `several CHECK constraints produce several invariants`() {
            val fsh =
                fsh(
                    """
                CREATE TABLE t (
                    a INT NOT NULL,
                    b INT NOT NULL,
                    CONSTRAINT chk_a CHECK (a > 0),
                    CONSTRAINT chk_b CHECK (b > 0)
                );
            """,
                )
            assertContains(fsh, "* obeys chk-a", "* obeys chk-b")
        }
    }

    // ── UNIQUE constraint ─────────────────────────────────────────────────

    @Nested
    inner class UniqueConstraint {
        @Test
        fun `UNIQUE column wrapped in BackboneElement with uniqueKeyName child fixed to the resolved name`() {
            val fsh =
                fsh(
                    """
                CREATE TABLE t (
                    code TEXT NOT NULL,
                    CONSTRAINT uq_code UNIQUE (code)
                );
            """,
                )
            assertContains(
                fsh,
                "* code 1..1 BackboneElement",
                "* code.uniqueKeyName 1..1 string",
                "* code.uniqueKeyName = \"UQ_CODE\"",
            )
        }
    }

    // ── Reference table: full case ─────────────────────────────

    @Nested
    inner class FullDdlToFshCase {
        private val ddl = """
            CREATE TABLE encounter (
                id         UUID        NOT NULL,
                start_date TIMESTAMP   NOT NULL,
                note       TEXT,
                CONSTRAINT pk_encounter PRIMARY KEY (id),
                CONSTRAINT chk_note CHECK (note IS NOT NULL OR start_date IS NOT NULL)
            );
        """

        @Test
        fun `full Logical block`() {
            val fsh = fsh(ddl)
            assertContains(
                fsh,
                "Logical: Encounter",
                "* id 1..1",
                "* startDate 1..1 dateTime",
                "* note 0..1 string",
                "* obeys chk-note",
                "isPrimaryKey",
            )
        }

        @Test
        fun `each rule line starts with a star or is blank`() {
            val fsh = fsh(ddl)
            val ruleLines =
                fsh
                    .lines()
                    .filter { it.isNotBlank() }
                    .filterNot { it.startsWith("//") }
                    .filterNot {
                        it.startsWith("Logical:") ||
                            it.startsWith("Parent:") ||
                            it.startsWith("Id:") ||
                            it.startsWith("Title:") ||
                            it.startsWith("Description:") ||
                            it.startsWith("Characteristics:") ||
                            it.startsWith("Invariant:") ||
                            it.startsWith("Expression:") ||
                            it.startsWith("Severity:")
                    }
            ruleLines.forEach { line ->
                assertTrue(
                    line.trimStart().startsWith("*"),
                    "Rule line without '*': «$line»",
                )
            }
        }
    }
}
